# Copy Number Variations

- Comparison ID: `r comparisonID`

```{r}
cnvs_final_cns <- paste(comparisonID, params$cnvs_final_cns, sep = '.')[1] 

# reference data for plotting
# ordered factor level for chroms
chrom_order <- c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", 
                 "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", 
                 "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", 
                 "chr22", "chrX", "chrY", "chrM")
chrom_key <- setNames(object = as.character(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 
                                              12, 13, 14, 15, 16, 17, 18, 19, 20, 
                                              21, 22, 23, 24, 25)), 
                      nm = chrom_order)
chrom_order <- factor(x = chrom_order, levels = rev(chrom_order))

cnvs <- list()

tryCatch(
        {
            cnvs[["cns"]] <- read.delim(file = cnvs_final_cns, header = TRUE, sep = '\t')
            cnvs[["cns"]][["chromosome"]] <- factor(x = cnvs[["cns"]][["chromosome"]], 
                                levels = chrom_order)
            cnvs[["cns"]][["gain_loss"]] <- factor(ifelse(cnvs[["cns"]][["log2"]] > 0, "gain", "loss"), 
                                                   levels = c("gain", "loss"))
            
            
            cnvs[["cnvplot"]] <- ggplot(data = cnvs[["cns"]], 
                                        aes(x = start, 
                                            xend = end, 
                                            y = log2, 
                                            yend = log2, 
                                            label = gene,
                                            color = gain_loss
                                        )) + 
                # geom_point(size = 4) + # use this with ggplotly
                geom_segment(size = 2, lineend = "round") + # does not work right in ggplotly
                geom_hline(yintercept = 0) +
                facet_grid(.~chromosome, scales = "free_x", drop = FALSE) +
                theme_bw() + 
                theme(axis.title.x=element_blank(),
                      axis.text.x=element_blank(),
                      axis.ticks.x=element_blank(), 
                      panel.grid = element_blank()) + 
                scale_y_continuous(limits = c( -max(cnvs[["cns"]][["log2"]]) - 0.5, 
                                               max(cnvs[["cns"]][["log2"]]) + 0.5)) + 
                theme(legend.position="none") + 
                scale_color_manual(values = c("green", "red"))

        },
        error=function(cond) {
            return(NA)
        }
    )
```

## Plots

```{r, results='asis', warning = FALSE, fig.width=12}
if (length(cnvs) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    print(cnvs[["cnvplot"]])
}

```

## Table

```{r, results='asis'}
if (length(cnvs) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    datatable(cnvs[["cns"]], options = list(pageLength = 10))
}

```


```{r}
save.image("cnvs.Rdata", compress = TRUE)
```