# Genomic Signatures

```{r signatures_load}
signatures_Rds <- paste(sampleID, params$signatures_Rds, sep = '.')[1] 
signatures_plot_Rds <- paste(sampleID, params$signatures_plot_Rds, sep = '.')[1]
signatures_pieplot_Rds <- paste(sampleID, params$signatures_pieplot_Rds, sep = '.')[1]

signatures <- tryCatch(
        {
            output <- list()

            output[["signatures"]] <- readRDS(signatures_Rds)
            output[["signatures_plot"]] <- readRDS(signatures_plot_Rds)
            output[["signatures_pieplot"]] <- readRDS(signatures_pieplot_Rds)
            
            weights <- as.data.frame(t(output[["signatures"]][["weights"]]))
            weights <- weights[ order(-weights[,1]), , drop=FALSE]
            
            output[["weights"]] <- weights
            
            return(output)
        },
        error=function(cond) {
            return(list())
        },
        warning=function(cond) {
            return(list())
        }
    )
# get_signatures <- function(){
#     signatures <- tryCatch(
#         {
#             output <- list()
# 
#             signaturesRds <- input_files[grep(pattern = paste0(sampleID, '.*_signatures.Rds$'), x = input_files)][1]
#             signatures <- readRDS(signaturesRds)
# 
#             signatures_plotRds <- input_files[grep(pattern = paste0(sampleID, '.*_signatures_plot.Rds$'), x = input_files)][1]
#             signatures_plot <- readRDS(signatures_plotRds)
# 
#             signatures_pieplotRds <- input_files[grep(pattern =  paste0(sampleID, '.*_signatures_pieplot.Rds$'), x = input_files)][1]
#             signatures_pieplot <- readRDS(signatures_pieplotRds)
# 
#             weights <- as.data.frame(t(signatures[["weights"]]))
#             weights <- weights[ order(-weights[,1]), , drop=FALSE]
# 
#             output[["signatures"]] <- signatures
#             output[["signatures_plot"]] <- signatures_plot
#             output[["signatures_pieplot"]] <- signatures_pieplot
#             output[["weights"]] <- weights
#             output
#         },
#         error=function(cond) {
#             return(list())
#         },
#         warning=function(cond) {
#             return(list())
#         }
#     )
#     return(signatures)
# }
# signatures <- get_signatures()
```

```{r signatures_weights, results='asis'}
# if (length(signatures) < 1){
#     cat('\n\n- __No results found__\n\n')
# } else {
#     cat(sprintf('\n\n## %s\n\n', "Weights"))
#     signatures[["weights"]]
# }
```

```{r signatures_plots, fig.width=10, fig.height=8, warning=FALSE, results='asis'}
# if (length(signatures) < 1){
#     cat('\n\n- __No results found__\n\n')
# } else {
#     cat(sprintf('\n\n## %s\n\n', "Plots"))
#     signatures[["signatures_pieplot"]]
#     signatures[["signatures_plot"]]
# }
```
```{r}
save.image("signatures.Rdata", compress = TRUE)
```