# base starting container for NGS580 analysis pipeline containers
FROM ubuntu:16.04

MAINTAINER Stephen M. Kelly

# location for apps
RUN mkdir /opt/bin
ENV PATH="/opt/bin:${PATH}"

# location for data
RUN mkdir /data
