```{r}
failed_log <- params$failed_log
failed_pairs_log <- params$failed_pairs_log
```

# Failed Samples

Samples that did not complete the full pipeline for the described reasons.

## Samples

```{r, results='asis'}
if(file.exists(failed_log)){
    failed <- read.delim(file = failed_log, 
                         header = TRUE, 
                         sep = '\t', 
                         check.names = FALSE, 
                         stringsAsFactors = FALSE)
    save.image(file = 'failed.loaded.Rdata', compress = TRUE)
    
    # try to fix header; sometimes it shows up halfway through the table
    if(any(grepl(pattern = "Program", x = failed[,2]))){
        # find row that has the headers
        colnames_rownum <- which(failed[,2] == "Program")[1]
        new_colnames <- as.character(failed[colnames_rownum,])
        old_colnames <- names(failed)
        names(old_colnames) <- new_colnames

        # remove the row that has headers
        failed <- failed[-colnames_rownum, ]
        names(failed) <- new_colnames

        # add old row back
        failed <- rbind(old_colnames, failed)

    }
    
    
    if(nrow(failed) > 0){
        DT::datatable(data = failed[names(failed)[!names(failed) %in% "Files"]],
              options = list(pageLength = 5),
              class = 'cell-border stripe')

    } else {
        cat('- none\n\n')
    }
}
```

## Tumor-Normal Pairs

```{r, results='asis', warning=FALSE}
if(file.exists(failed_pairs_log)){
    failed_pairs <- read.delim(file = failed_pairs_log, 
                               header = TRUE, 
                               sep = '\t', 
                               check.names = FALSE, 
                               stringsAsFactors = FALSE)
    save.image(file = 'failed.loaded.Rdata', compress = TRUE)
    
    # try to fix header; sometimes it shows up halfway through the table
    if(any(grepl(pattern = "Comparison", x = failed_pairs[,1]))){
        # find row that has the headers
        colnames_rownum <- which(failed_pairs[,1] == "Comparison")[1]
        new_colnames <- as.character(failed_pairs[colnames_rownum,])
        old_colnames <- names(failed_pairs)
        names(old_colnames) <- new_colnames
        
        # remove the row that has headers
        failed_pairs <- failed_pairs[-colnames_rownum, ]
        names(failed_pairs) <- new_colnames
        
        # add old row back 
        failed_pairs <- rbind(old_colnames, failed_pairs)
        
    }
    
    if(nrow(failed_pairs) > 0){
        DT::datatable(data = failed_pairs[, names(failed_pairs)[!names(failed_pairs) %in% c("Files", "")]],
              options = list(pageLength = 5),
              class = 'cell-border stripe')
    } else {
        cat('- none\n\n')
    }
}
```

```{r}
save.image(file = 'failed.Rdata', compress = TRUE)
```
