```{r load_annotations}
# loads variant information from 'all_annotations.tsv' file
annotations_file <- params$annotations_file
annotations <- read.delim(file = annotations_file, 
                          header = TRUE, 
                          sep = '\t', 
                          check.names = FALSE, 
                          na.strings = c('.'))

# sort the Sample levels
annotations[["Sample"]] <- factor(x = annotations[["Sample"]], 
                                  levels = sort(unique(as.character(annotations[["Sample"]]), 
                                                       decreasing = TRUE)))
```

# Variants

## MuTect2

Somatic variant calling with GATK MuTect2 [@GATKToolkit], using matched tumor-normal pairs.

```{r mutect2}
make_mutect2_plots <- function(df){
    plots <- list()
    if(is.data.frame(df)){
        if(nrow(df) > 0){
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            mutect2_counts <- ggplot(data = df, aes(x = Sample)) +
                geom_bar(stat="count") + 
                ggtitle("Number of Variants") + 
                coord_flip() +
                theme_bw() +
                theme(panel.grid.minor = element_blank()) 
            
            plots[['counts']] <- list(
                plot = mutect2_counts,
                subheader = 'Counts'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            mutect2_qual <- ggplot(data = df, aes(x=Sample, y=QUAL, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Quality Scores") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['qual']] <- list(
                plot = mutect2_qual,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            mutect2_dp <- ggplot(data = df, aes(x=Sample, y=TUMOR.AD.TOTAL, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Tumor Depth of Coverage") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['dp']] <- list(
                plot = mutect2_dp,
                subheader = 'Tumor Depth of Coverage'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            mutect2_af <- ggplot(data = df, aes(x=Sample, y=TUMOR.AF, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Tumor Allele Frequency") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['af']] <- list(
                plot = mutect2_af,
                subheader = 'Tumor Allele Frequency'
            )
        }
    }
    return(plots)
}

mutect2_plots <- make_mutect2_plots(annotations[annotations[["VariantCaller"]] == 'MuTect2', ])

```

```{r mutect2_print, results='asis'}
# print any results found
if (length(mutect2_plots) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    for(item in mutect2_plots){
        subplot<- item[["plot"]]
        subheader <- item[["subheader"]]
        
        cat(sprintf('\n\n### %s\n\n', subheader))
        print(subplot)
    }
}
```

## LoFreq Somatic

Somatic variant calling with LoFreq [@LoFreq], using matched tumor-normal pairs. 


```{r}
# ~~~~~~~ FUNCTIONS ~~~~~~~ #
make_lofreq_somatic_plots <- function(df){
    plots <- list()
    if(is.data.frame(df)){
        if(nrow(df) > 0){
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_counts <- ggplot(data = df, aes(x = Sample)) +
                geom_bar(stat="count") + 
                ggtitle("Number of Variants") + 
                coord_flip() +
                theme_bw() +
                theme(panel.grid.minor = element_blank()) 
            
            plots[['counts']] <- list(
                plot = lofreq_counts,
                subheader = 'Counts'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_qual <- ggplot(data = df, aes(x=Sample, y=QUAL, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Quality Scores") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['qual']] <- list(
                plot = lofreq_qual,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_dp <- ggplot(data = df, aes(x=Sample, y=DP, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Depth of Coverage") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['dp']] <- list(
                plot = lofreq_dp,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_af <- ggplot(data = df, aes(x=Sample, y=AF, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Allele Frequency") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['af']] <- list(
                plot = lofreq_af,
                subheader = 'Allele Frequency'
            )
        }
    }
    return(plots)
}

# ~~~~~~~ RUN ~~~~~~~ #
lofreq_somatic_plots <- make_lofreq_somatic_plots(annotations[annotations[["VariantCaller"]] == 'LoFreqSomatic', ])
```

```{r, results='asis'}
# print any results found
if (length(lofreq_somatic_plots) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    
    for(item in lofreq_somatic_plots){
        subplot<- item[["plot"]]
        subheader <- item[["subheader"]]
        
        cat(sprintf('\n\n### %s\n\n', subheader))
        print(subplot)
    }
}
```


## GATK HaplotypeCaller

Variant calling with GATK HaplotypeCaller [@GATKToolkit]

```{r haplotypecaller}
# ~~~~~~~ FUNCTIONS ~~~~~~~ #
make_haplotypecaller_plots <- function(df){
    plots <- list()
    if(is.data.frame(df)){
        if(nrow(df) > 0){
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            haplotypecaller_counts <- ggplot(data = df, aes(x = Sample)) +
                geom_bar(stat="count") + 
                ggtitle("Number of Variants") + 
                coord_flip() +
                theme_bw() +
                theme(panel.grid.minor = element_blank()) 
            
            plots[['counts']] <- list(
                plot = haplotypecaller_counts,
                subheader = 'Counts'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            haplotypecaller_qual <- ggplot(data = df, aes(x=Sample, y=QUAL, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Quality Scores") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['qual']] <- list(
                plot = haplotypecaller_qual,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            haplotypecaller_dp <- ggplot(data = df, aes(x=Sample, y=DP, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Depth of Coverage") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['dp']] <- list(
                plot = haplotypecaller_dp,
                subheader = 'Depth of Coverage'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            haplotypecaller_af <- ggplot(data = df, aes(x=Sample, y=AF, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Allele Frequency") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['af']] <- list(
                plot = haplotypecaller_af,
                subheader = 'Allele Frequency'
            )
        }
    }
    return(plots)
}

# ~~~~~~~ RUN ~~~~~~~ #
haplotypecaller_plots <- make_haplotypecaller_plots(annotations[annotations[["VariantCaller"]] == 'HaplotypeCaller', ])
```

```{r haplotypecaller_print, results='asis'}
# print any results found
if (length(haplotypecaller_plots) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    for(item in haplotypecaller_plots){
        subplot<- item[["plot"]]
        subheader <- item[["subheader"]]
        
        cat(sprintf('\n\n### %s\n\n', subheader))
        print(subplot)
    }
}
```

## LoFreq

Variant calling results from the LoFreq program [@LoFreq]

```{r lofreq}
# ~~~~~~~ FUNCTIONS ~~~~~~~ #
make_lofreq_plots <- function(df){
    plots <- list()
    if(is.data.frame(df)){
        if(nrow(df) > 0){
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_counts <- ggplot(data = df, aes(x = Sample)) +
                geom_bar(stat="count") + 
                ggtitle("Number of Variants") + 
                coord_flip() +
                theme_bw() +
                theme(panel.grid.minor = element_blank()) 
            
            plots[['counts']] <- list(
                plot = lofreq_counts,
                subheader = 'Counts'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_qual <- ggplot(data = df, aes(x=Sample, y=QUAL, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Quality Scores") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['qual']] <- list(
                plot = lofreq_qual,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_dp <- ggplot(data = df, aes(x=Sample, y=DP, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Depth of Coverage") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['dp']] <- list(
                plot = lofreq_dp,
                subheader = 'Quality Scores'
            )
            # ~~~~~~~~~~~~~~~~~~~~~~~~~ # 
            lofreq_af <- ggplot(data = df, aes(x=Sample, y=AF, fill=Sample)) + 
                geom_boxplot() + 
                guides(fill=FALSE) + 
                coord_flip() + 
                ggtitle("Allele Frequency") + 
                theme_bw() +
                theme(panel.grid.minor = element_blank())
            
            plots[['af']] <- list(
                plot = lofreq_af,
                subheader = 'Allele Frequency'
            )
        }
    }
    return(plots)
}

# ~~~~~~~ RUN ~~~~~~~ #
lofreq_plots <- make_lofreq_plots(annotations[annotations[["VariantCaller"]] == 'LoFreq', ])
```

```{r plot_variants, results='asis'}
# print any results found
if (length(lofreq_plots) < 1){
    cat('\n\n- __No results found__\n\n')
} else {
    
    for(item in lofreq_plots){
        subplot<- item[["plot"]]
        subheader <- item[["subheader"]]
        
        cat(sprintf('\n\n### %s\n\n', subheader))
        print(subplot)
    }
}
```


```{r}
# save environment to file
save.image(file="variants.Rdata",compress = TRUE)
```
